### ISSUE TITLE
Suggestion for exporting `configs`

### ISSUE THREAD

**Issue by benmccann** [es-tooling/eslint-plugin-depend#20]
The example in the readme is:

```
import {configs} from 'eslint-plugin-depend';

export default [
  configs['flat/recommended'],

  // or if you want to specify `files`, or other options
  {
    ...configs['flat/recommended'],
    files: ['test/**/*.js']
  }
];
```

When I see `configs` in the code it's hard to know that it's for `eslint-plugin-depend` vs another plugin. And if any other eslint plugin also calls their export `configs` you will get a collision. Perhaps it should be called `dependConfigs`?

I took a look at what other eslint plugins are doing and the most common pattern would seem to be to do this:

```
import depend from 'eslint-plugin-depend';

export default [
  depend.configs['flat/recommended'],

  // or if you want to specify `files`, or other options
  {
    ...depend.configs['flat/recommended'],
    files: ['test/**/*.js']
  }
];
```

The trouble with default exports though is that they don't really play great across cjs/esm, which is why I think that `import { dependConfigs } from 'eslint-plugin-depend';` might work out better long-term

**Comment by 43081j** [comment]
it may just be a documentation thing

i'd probably recommend one of these patterns rather than what's in the readme currently:

```ts
import {configs as dependConfigs} from 'eslint-plugin-depend';

// or
import * as depend from 'eslint-plugin-depend';

depend.configs;
```

**Comment by benmccann** [comment]
I'd thought about the first, which is what led me to the suggestion. Because I thought if we were going to officially recommend that people always alias it then it'd be nice to save them that step.

I like the second suggestion of `import *` though. It's shorter and avoids the awkward alias
