### ISSUE TITLE
Option for allowing some "banned" dependencies

### ISSUE THREAD

**Issue by zloirock** [es-tooling/eslint-plugin-depend#23]
In some cases, it could be good to have an option to allow some "banned" dependencies - for example, it's not always possible to replace it with an alternative immediately, and `.json` files do not allow `eslint-disable` comments.

**Comment by 43081j** [comment]
that makes sense to me, some kind of allow list we can pass to the `ban-dependencies` rule

would be open to contributions to introduce that
