### ISSUE TITLE
It seems you forgot to publish the new version on NPM

### ISSUE THREAD

**Issue by zloirock** [es-tooling/eslint-plugin-depend#33]
<img width="789" alt="Снимок экрана 2024-08-11 в 21 36 53" src="https://github.com/user-attachments/assets/8dff48a0-0389-41f6-89db-dcf201743c2f">

**Comment by 43081j** [comment]
the workflow failed. im a bit stuck here as nothing has changed on our end

seems like github is at fault

**Comment by 43081j** [comment]
Fixed 👍
